In [45]:
from typing import Optional, List, Any

## Задача 1
### Reversed integer

Вам дано число целого типа ``a``. Вам необходимо написать функцию, которая принимает это число на вход, а на выход выдает целое число, цифры в котором записаны в обратном порядке.


**Sample Input 1:**

``
a = 123
``

**Sample Output 1:**

``321``

**Sample Input 2:**

``
a = 120
``

**Sample Output 2:**

``21``

**Sample Input 3:**

``
-123
``

**Sample Output 3:**

``321``

In [2]:
def reverse_number(a : int) -> int:
    """
    Находит число, цифры в котором записаны в обратном порядке

    Args:
        a(int):  Число целого типа, которое необходимо преобразовать

    Returns:
        int: Число целого типа, цифры в котором записаны в обратном порядке
    """

    reversed_a: int=int(str(a)[::-1])
    return reversed_a

In [4]:
number_str: str = input("Введите число: ")
if number_str[0] == "-":
    number_str=number_str[1:]
if number_str.isnumeric():
    number: int=int(number_str)
    print("Перевернутое число: ", reverse_number(number))
else:
    print("Вы ввели неверное число")


Перевернутое число:  321


# Задача 2
## Выколотый квадрат


Напишите функцию, которая принимает единственное число ``n: int``. Это число определяет длину стороны квадрата. Функция должна нарисовать квадрат из звездочек, при этом звездочки должны быть только на ребрах квадрата, центр должен быть выколот.

**Sample Input 1:**

``
n = 5
``

**Sample Output 1:**
```
* * * * *
*       *
*       *
*       *
* * * * *

```

In [5]:
def make_square(n: int) -> None:
    """
    Рисует квадрат из звездочек
    Args:
        n: Длина стороны квадрата

    Returns:
        None: Ничего не возвращает

    """

    if n<2:
        print("Сторона квадрата не может быть меньше 2")
        return

    for i in range(n):
        if i==0 or i==n-1:
            print(" ".join("*"*n))
        else:
            print((" "*(2*n-3)).join("*"*2))


number_str: str = input("Введите длину стороны квадрата: ")
if number_str[0] == "-":
    number_str=number_str[1:]
if number_str.isnumeric():
    number: int=int(number_str)
    make_square(number)
else:
    print("Вы ввели неверное число")

* * * * *
*       *
*       *
*       *
* * * * *


# Задача 3
## Пермутации

Вам дан массив с целыми числами ``nums``. Напишите функцию, которая принимает на вход данный массив и возвращает все возможные пермутации с данными числами. Возвращать массивы можно в любом порядке.

**Sample Input 1:**

``
nums = [1,2,3]
``

**Sample Output 1:**

``[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]``

**Sample Input 2:**

``
nums = [0,1]
``

**Sample Output 2:**

``[[0,1],[1,0]]``

**Sample Input 3:**

``
nums = [1]
``

**Sample Output 3:**

``[[1]]``

Вариант 1

In [46]:
import itertools

def permutations(numbers: List[int]) -> List[Any]:
    """
    Возвращает все возможные пермутации данных массива

    Args:
        numbers(List[int]): Массив с целыми числами

    Returns:
        List[Any]: Массив со всеми возможными пермутациями исходного массива
    """

    return [list(item) for item in itertools.permutations(numbers)]

numbers_str: str = input("Введите последовательность чисел через пробел: ")
nums: list[int] = [int(item) for item in numbers_str.split(' ')]
print(permutations(nums))

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]


Вариант 2

In [47]:
def permutations2(numbers: List[int]) -> List[Any]:
    """
    Возвращает все возможные пермутации данных массива

    Args:
        numbers(List[int]): Массив с целыми числами

    Returns:
        List[Any]: Массив со всеми возможными пермутациями исходного массива
    """

    if len(numbers) <= 1:
        yield numbers
        return
    for perm in permutations2(numbers[1:]):
        for i in range(len(numbers)):
            # nb elements[0:1] works in both string and list contexts
            y=perm[:i] + numbers[0:1] + perm[i:]
            yield y


numbers_str: str = input("Введите последовательность чисел через пробел: ")
nums: list[int] = [int(item) for item in numbers_str.split(' ')]

print(list(permutations2(nums)))

[[1, 2, 3], [2, 1, 3], [2, 3, 1], [1, 3, 2], [3, 1, 2], [3, 2, 1]]


# Задача 4
## Почти двойной факториал
Дано натуральное $N \leqslant 100$.  Выведите произведение всех чётных натуральных чисел, не превосходящих $N$.

In [18]:
def almost_double_factorial(n:int) -> int:
    """
    Вычисляет почти двойной факториал

    Args:
        n(int): Натуральное число

    Returns:
        int: Почти двойной факториал
    """

    factorial : int =1
    for x in range(2,n+1,2) :
        factorial *= x
    return factorial

In [23]:
N = 25
#YOUR CODE
N_double_fact = almost_double_factorial(N)
assert N_double_fact == 1961990553600, "Something is wrong! Please try again"

N = 100
N_double_fact = almost_double_factorial(N)
assert N_double_fact == 34243224702511976248246432895208185975118675053719198827915654463488000000000000, "Something is wrong! Please try again"

# Задача 5
## Хитрая сортировка

Пусть у нас есть следующий список, в котором элементы -- tuple из строк:

``items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]``

Мы хотим отсортировать этот список по последней букве второго элемента каждого ``tuple``, т.е. получить такой список:

``sorted_items = [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')]``.
Что нужно вставить вместо "###" в следующем выражении, чтобы получить сортировку?

``sorted_items = sorted(items, key=lambda x: ###)``

In [22]:
items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]

sorted_items = sorted(items, key=lambda x: x[1][-1])
print(sorted_items)

assert sorted_items == [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')], \
"Something is wrong! Please try again"

[('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')]


# Задача 6
## Еще строки

Вашей программе на вход подаются три строки ``s, a, b``, состоящие из строчных латинских букв.
За одну операцию вы можете заменить все вхождения строки ``a`` в строку ``s`` на строку ``b``.

Например, ``s = "abab", a = "ab", b = "ba"``, тогда после выполнения одной операции строка ``s`` перейдет в строку ``"baba"``, после выполнения двух и операций – в строку ``"bbaa"``, и дальнейшие операции не будут изменять строку ``s``.

Необходимо узнать, после какого минимального количества операций в строке ``s`` не останется вхождений строки ``a``. Если операций потребуется более 1000, выведите ``Impossible``.

Выведите одно число – минимальное число операций, после применения которых в строке ``s`` не останется вхождений строки ``a``, или ``Impossible``, если операций потребуется более 1000.

**Sample Input 1:**

``
ababa
a
b
``

**Sample Output 1:**

``1``

**Sample Input 2:**

``ababa
b
a``

**Sample Output 2:**

``1``

**Sample Input 3:**

``ababa
c
c``

**Sample Output 3:**

``0``

**Sample Input 4:**

``ababac
c
c``

**Sample Output 4:**

``Impossible``


In [21]:
def my_func(s: str,a: str,b: str) -> any:
    """
    Определяет, после какого минимального количества операций замены в строке s строки a на строку b не останется вхождений строки a
    Args:
        s(str): Строка, состоящая из строчных латинских букв
        a(str): Строка, состоящая из строчных латинских букв
        b(str): Строка, состоящая из строчных латинских букв

    Returns:
        any: Минимальное количество операций замены в строке s строки a на строку b или сообщение о невозможности определить это значение
    """

    new_str: str=s
    count: int=0

    while a in new_str:
        count +=1
        if count >1000:
            return "Impossible"

        new_str=new_str.replace(a,b)

    return str(count)


source_string = input("Введите s, a, b через пробел: ")
s, a, b = source_string.split(' ')

print(my_func(s, a, b))

2


# Задача 7
## Создание массивов
Дан массив $A[0,\ldots,N-1]$. Напишите функцию, принимающую один обязательный аргумент A и один опциональный аргумент ``erase``, по умолчанию равный 1. Возвратите массив $B[0,\ldots, N-1]$, где $B_i = A_0 + \ldots + A_{i}$ --- массив частичных сумм массива $A$, предварительно удалив из массива $B$ все элементы, равные erase. Постарайтесь сделать это за линейное время без использования Numpy.

Вариант 1

In [48]:
def cumsum_and_erase(massive: List[int], erase: int= 1) -> List[int]:
    """
    Возвращает массив частичных сумм исходного массива `massive`, предварительно удалив из него все элементы, равные erase. Вариант 1

    Args:
        massive(List[int]): Исходный массив
        erase(int): Значение элементов, которые надо удалить

    Returns:
        List[int]: Массив частичных сумм
    """

    result: List[int] = []
    if not massive :
        return result

    summa: int =0
    for item in massive:
        summa += item
        if summa != erase:
            result.append(summa)

    return result


A = [5, 1, 4, 5, 14]
B = cumsum_and_erase(A, erase=10)
print(B)

assert B == [5, 6, 15, 29], "Something is wrong! Please try again"

[5, 6, 15, 29]


Вариант 2

In [49]:
def cumsum_and_erase2(massive: List[int], erase: int= 1) -> List[int]:
    """
    Возвращает массив частичных сумм исходного массива `massive`, предварительно удалив из него все элементы, равные erase. Вариант 2

    Args:
        massive(List[int]): Исходный массив
        erase(int): Значение элементов, которые надо удалить

    Returns:
        List[int]: Массив частичных сумм
    """

    result: List[int] = []
    if not massive :
        return result

    summa: int =0
    def part_sum(number):
         nonlocal  summa
         summa += number
         return summa

    result=filter( lambda x: x != erase, map (part_sum,  massive))
    return list(result)


A = [5, 1, 4, 5, 14]
B = cumsum_and_erase2(A, erase=10)
print(B)

assert B == [5, 6, 15, 29], "Something is wrong! Please try again"


[5, 6, 15, 29]


Вариант 3

In [50]:
def cumsum_and_erase3(massive: List[int], erase: int= 1) -> List[int]:
    """
    Возвращает массив частичных сумм исходного массива `massive`, предварительно удалив из него все элементы, равные erase. Вариант 3

    Args:
        massive(List[int]): Исходный массив
        erase(int): Значение элементов, которые надо удалить

    Returns:
        List[int]: Массив частичных сумм
    """

    result: List[int] = []
    if not massive :
        return result

    def part_sum():
        summa: int =0
        for num in massive:
            summa += num
            if summa == erase:
                continue
            yield summa

    result=[i for i in part_sum()]
    return result


A = [5, 1, 4, 5, 14]
B = cumsum_and_erase3(A, erase=10)
print(B)

assert B == [5, 6, 15, 29], "Something is wrong! Please try again"

[5, 6, 15, 29]


# Задача 8
## Обработка текста
Дан список текстов, слова в которых разделены пробелами (можно считать, что знаков препинания нет). Часть слов является "мусорными": в них присутствуют цифры и спецсимволы. Отфильтруйте такие слова из каждого текста. Используйте функции ``str.split``, ``str.isalpha``, ``str.join``, а также [генератор filter](http://pythonicway.com/python-functinal-programming).

In [51]:
sentences = ['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100']

def process(sentences: List[str]) -> List[str]:
    """
    Фильтрует мусорные слова из каждого текста в списке

    Args:
        sentences(List[str]):  Исходный список текстов

    Returns:
        List[str]: Cписок текстов без мусорных слов
    """

    if not sentences :
        return []

    result =[" ".join(word for word in sentence.split(" ") if word.isalpha()) for sentence in sentences]
    return result


print(process(sentences))
assert process(sentences) == ['thousand devils', 'My name is', 'Room costs'], \
"Something is wrong! Please try again"

['thousand devils', 'My name is', 'Room costs']


# Задача 9
## Расстояние Хэмминга

Вам даны две строки, ``a`` и ``b`` одинаковой длины. Необходимо посчитать расстояние Хэмминга между ними, которое определяется как количество символов, которые не совпадают между двумя строками в одинаковой позиции.

**Sample Input 1:**

```
a = 'AGCT'
b = 'ACGT'
hamming(a, b)
```

**Sample Output 1:**

``2``

In [29]:
def hamming(string_a: str, string_b: str) -> int:
    """
    Определяет расстояние Хэмминга между словами
    Args:
        string_a: строка 1
        string_b: строка 2

    Returns:
        int: Расстояние Хэмминга между словами
    """
    r2: int = sum((a==b for a, b in zip(string_a, string_b)))
    return r2

print(hamming("AGCTru", "ACGTrwc") )
assert hamming("AGCT", "ACGT") == 2

3


## Задание 10
### Numpy
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [33]:
import numpy as np
import random
import scipy.stats as sps

In [34]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
print("Размерность матрицы a: ", np.ndim(a))
print("Размерность матрицы b: ", np.ndim(b))

print("Размер матрицы a: ", np.shape(a)[0], "x", np.shape(a)[1])
print("Размер матрицы b: ", np.shape(b)[0], "x", np.shape(b)[1])
# ========
print(a)
print(b)

Размерность матрицы a:  2
Размерность матрицы b:  2
Размер матрицы a:  100 x 100
Размер матрицы b:  100 x 100
[[0.85336848 0.96886606 0.63302641 ... 0.55401561 0.25903881 0.16155325]
 [0.19720296 0.28881423 0.47628779 ... 0.18037487 0.93173331 0.50381734]
 [0.72757432 0.23404836 0.9553348  ... 0.36678324 0.27437376 0.38224171]
 ...
 [0.83305215 0.03299343 0.80554189 ... 0.10234039 0.0614844  0.70794901]
 [0.88646012 0.7366452  0.80231146 ... 0.11785883 0.31198277 0.80889341]
 [0.27983096 0.64098971 0.17676034 ... 0.91721537 0.33221945 0.48615894]]
[[0.0469782  0.05888079 0.73542558 ... 0.16168686 0.4569475  0.10454472]
 [0.57900108 0.33693213 0.40972249 ... 0.84063534 0.2682069  0.3552525 ]
 [0.77516258 0.98312033 0.9120319  ... 0.20518666 0.47303637 0.40131057]
 ...
 [0.51641969 0.81830374 0.88851271 ... 0.90435633 0.33840834 0.67489005]
 [0.80890093 0.45881203 0.01184292 ... 0.98493785 0.45348921 0.23089534]
 [0.74635084 0.73463516 0.54073332 ... 0.68320673 0.1052257  0.70417264]]


In [52]:
def mult(a: List[float], b: List[float]) -> List[float]:
    """
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c
    Реализуйте умножение матриц без использования функций из пакета numpy (может помочь функция zip)

    Args:
        a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
        b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент

    Returns:
        list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    """

    b_transp = list(zip(*b))
    result=[[sum(a_item*b_item for a_item, b_item in zip(a_row, b_col)) for b_col in b_transp] for a_row in a]

    return result

In [40]:
def np_mult(a:np.array, b:np.array) -> np.array:
     """
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц, используя функции из пакета numpy

    Args:
        a: np.array[size, size] --- первая матрица-аргумент
        b: np.array[size, size] --- вторая матрица-аргумент

    Returns:
        np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    """

     return a.dot(b)

In [41]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 107 ms, sys: 3.44 ms, total: 111 ms
Wall time: 110 ms


In [56]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.97 ms, sys: 335 µs, total: 2.31 ms
Wall time: 269 µs


In [43]:
# проверим корректность
assert np.allclose(np.array(M1), M2)
