# Разогрев

## Задание 1

Иногда, когда нужно создавать много однотипных лямбда функций, еще удобнее будет создать функцию, которая будет их генерировать.

Реализуйте функцию ``mod_checker(x, mod=0)``, которая будет **возвращать лямбда функцию** от одного аргумента ``y``, которая будет возвращать ``True``, если остаток от деления ``y`` на ``x`` равен ``mod``, и ``False`` иначе.

Если в ``return`` вашей функции написано выражение, отличное от лямбда функции - задание считается проваленным

**Sample:**

```python
mod_3 = mod_checker(3)

print(mod_3(3)) # True
print(mod_3(4)) # False

mod_3_1 = mod_checker(3, 1)
print(mod_3_1(4)) # True
```

In [2]:
def mod_checker(x: int, mod: int = 0):
    """
    Возвращает лямбда функцию от одного аргумента y, которая будет возвращать True, если остаток от деления y на x равен mod, и False иначе.

    Args:
        x: Целое число
        mod: Целое число

    Returns:
        Функция, возвращающая True или False
    """

    return lambda y: True if y % x == mod else False


mod_3 = mod_checker(3)
print(mod_3)
print(mod_3(3))  # True
print(mod_3(4))  # False

mod_3_1 = mod_checker(3, 1)
print(mod_3_1(4))  # True

<function mod_checker.<locals>.<lambda> at 0x7f176564f7f0>
True
False
True


# Numpy

In [4]:
import numpy as np

## Задание 2
Напишите функцию, которая принимает один аргумент - ``n``. Функция должна создать нампаевскую матрицу размером ``(n, n)`` и залить ее шахматным узором. Порядок узора не имеет значения, важен общий паттерн.

**Sample:**
```python
chess_maze(8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```



In [5]:
def chess_board(n: int):
    """
    Создает нампаевскую матрицу размером (n, n) и заливает ее шахматным узором
    Args:
        n: Число строк (столбцов)

    Returns:
        Матрица размером (n, n)
    """

    board = np.zeros((n, n), dtype=int)
    board[::2, 1::2] = 1
    board[1::2, ::2] = 1
    return board


print(chess_board(5))

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


## Задание 3
Напишите функцию, которая принимает 2 аргумента ``arr`` и ``exclude_values``. ``arr`` - это одномерный нампаевский массив, в котором необходимо поменять знак всем числам (инвертировать), которые есть в массиве ``exclude_values``. Действия необходимо делать прямо в исходном массиве, не создавая копий.

**Sample:**
```python
# Исходный вектор
arr = np.arange(10+1)
exclude_values = np.arange(4, 8)
 
my_func(arr, exclude_values)
array([ 0  1  2  3 -4 -5 -6 -7  8  9 10])
```

In [6]:
def invert_values(source_array, exclude_array) -> None:
    """
    Меняет знак всем числам, которые есть в массиве `exclude_values`

    Args:
        source_array(np.array):  Исходный вектор
        exclude_array(np.array):  Значения, для которых надо поменять знак

    Returns:
        None: ничего не возвращает
    """

    source_array[np.isin(arr, exclude_array)] *= -1


arr = np.arange(10 + 1)
exclude_values = np.arange(4, 8)
invert_values(arr, exclude_values)
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## Задание 4
Напишите функцию, которая принимает одномерный положительный нампаевский массив и минимум 4 раза выводит на экран (функция ``print``) этот же массив, в котором у элементов оставлена только целая часть. Все >= 4 раза функция должна использовать разные методы для извлечения целой части.

**Sample:**
```python
# Исходный вектор
arr = np.random.uniform(low=10, high=100,size=20)
# Исходный вектор arr:
arr
[99.54707368 49.26237526 80.50565073 10.10998238 16.39378916 60.64633657
 25.49637622 31.06574268 94.48636127 73.41204506 75.70638137 70.43830146
 72.28607422 40.59319738 57.85802554 35.39428061 55.25707514 48.00020145
 38.39449991 26.19085017]
 
my_func(arr)

[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
[99 49 80 10 16 60 25 31 94 73 75 70 72 40 57 35 55 48 38 26]
[99. 49. 80. 10. 16. 60. 25. 31. 94. 73. 75. 70. 72. 40. 57. 35. 55. 48.
 38. 26.]
```

В примере 5 выводов print из функции, просто чтобы были :)

In [7]:
def print_int(arr):
    """
    Извлечение целой части числа
    Args:
        arr: Массив исходных значений

    Returns:
        None: ничего не возвращает
    """

    print("Исходный вектор")
    print(arr)
    print("Преобразование к int8")
    print(np.int8(arr))
    print("Преобразование к int16")
    print(np.int16(arr))
    print("Преобразование к uint8")
    print(np.uint8(arr))
    print("Преобразование к uint16")
    print(np.uint16(arr))
    print("Преобразование к int")
    print(arr.astype(int))
    print("Преобразование arr.round(0)")
    print(arr.round(0))
    print("Преобразование np.round(arr,0)")
    print(np.round(arr, 0))
    print("Преобразование around(arr,0)")
    print(np.around(arr, 0))
    print("Преобразование np.fix(arr)")
    print(np.fix(arr))
    print("Преобразование np.floor(arr)")
    print(np.floor(arr))
    print("Преобразование np.ceil(arr)")
    print(np.ceil(arr))
    print("Преобразование np.trunc(arr)")
    print(np.trunc(arr))


my_arr = np.random.uniform(low=10, high=100, size=20)
print_int(my_arr)

Исходный вектор
[18.25101323 60.11338589 45.56375776 32.69762752 82.51511578 45.97678939
 28.50395545 12.3702594  83.0381056  74.34580285 47.36318378 42.44282893
 62.14868229 90.94298244 70.77370244 84.7788828  96.82530776 73.64928171
 22.96298825 24.35887957]
Преобразование к int8
[18 60 45 32 82 45 28 12 83 74 47 42 62 90 70 84 96 73 22 24]
Преобразование к int16
[18 60 45 32 82 45 28 12 83 74 47 42 62 90 70 84 96 73 22 24]
Преобразование к uint8
[18 60 45 32 82 45 28 12 83 74 47 42 62 90 70 84 96 73 22 24]
Преобразование к uint16
[18 60 45 32 82 45 28 12 83 74 47 42 62 90 70 84 96 73 22 24]
Преобразование к int
[18 60 45 32 82 45 28 12 83 74 47 42 62 90 70 84 96 73 22 24]
Преобразование arr.round(0)
[18. 60. 46. 33. 83. 46. 29. 12. 83. 74. 47. 42. 62. 91. 71. 85. 97. 74.
 23. 24.]
Преобразование np.round(arr,0)
[18. 60. 46. 33. 83. 46. 29. 12. 83. 74. 47. 42. 62. 91. 71. 85. 97. 74.
 23. 24.]
Преобразование around(arr,0)
[18. 60. 46. 33. 83. 46. 29. 12. 83. 74. 47. 42. 62. 91. 71. 8

## Задание 5
Напишите функцию, которая принимает два числа - ``N`` и ``p``. ``N`` - это размер стороны квадратной матрицы np.zeros, ``p`` - это количество индексов в матрице (p не превышает N*N), которые нужно заменить на случайные числа. Индексы и числа нужно выбирать случайно. Функция должна возвращать квадратную матрицу со стороной ``N``, в которой ровно ``p`` чисел заменены на случайные.

```python
my_func(N=6, p=4)

[[56.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [99.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 83.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   1.   0.]]
```

In [8]:
def my_func1(n: int, p: int):
    """
    Заменяет в матрице p элементов (не превышает n*n) на случайные числа. Вариант 1. Растягивание матрицы со случайными числами и заполнением нулями

    Args:
        n:  Размер стороны квадратной матрицы
        p:  Количество элементов для замены

    Returns:
        Матрица с замененными элементами
    """

    matrix = (np.random.randint(0, 150, size=p))
    matrix.resize(n * n)
    np.random.shuffle(matrix)
    matrix.shape = (n, n)

    return matrix


def my_func2(n: int, p: int):
    """
    Заменяет в матрице p элементов (не превышает n*n) на случайные числа. Вариант 2. Заполнение матрицы нулями
    и случайными числами с помощью генератора списка

    Args:
        n:  Размер стороны квадратной матрицы
        p:  Количество элементов для замены

    Returns:
        Матрица с замененными элементами
    """

    indexes = np.random.randint(0, n * n, size=p)
    matrix = np.array([np.random.randint(0, 150) if i in indexes else 0 for i in range(n * n)])
    matrix.shape = (n, n)

    return matrix


def my_func3(n: int, p: int):
    """
    Заменяет в матрице p элементов (не превышает n*n) на случайные числа.
    Вариант 3. Изменение матрицы через списочную индексацию

    Args:
        n:  Размер стороны квадратной матрицы
        p:  Количество элементов для замены

    Returns:
        Матрица с замененными элементами
    """

    matrix = np.zeros((n, n), dtype=float)
    indexes = np.random.randint(0, n * n, size=p)
    matrix.ravel()[indexes] = np.array(np.random.randint(0, 150, size=p))

    return matrix


print("Вариант 1")
print(my_func1(n=6, p=4))
print("Вариант 2")
print(my_func2(n=6, p=4))
print("Вариант 3")
print(my_func3(n=6, p=4))

Вариант 1
[[  0   0 136   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0  93   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0 147]
 [  0  47   0   0   0   0]]
Вариант 2
[[ 76   0   0  89 143   0]
 [  0   0   0   0   0   0]
 [  0   0 143   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]]
Вариант 3
[[  0.   0.   0.   0.   0.  80.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 113.   0.   0.]
 [  4.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0. 101.   0.   0.   0.   0.]]


# Pandas

In [10]:
import pandas as pd

pd.set_option("display.max_rows", 20)
pd.set_option("display.max_columns", 20)
pd.set_option("display.precision", 4)
pd.set_option("plotting.backend", "matplotlib")

# Задание 6

Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и четыре наблюдения в каждой колонке:

```
type value
B    18.

B    20.

C    10.

C    -10.
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)

In [11]:
my_data = pd.DataFrame({'type': ['B', 'B', 'C', 'C'], 'value': [18, 20, 10, -10]})
print(my_data.memory_usage())
old_mem = sum(my_data.memory_usage().values)
print('Всего байт было (байт): ', old_mem)

Index    128
type      32
value     32
dtype: int64
Всего байт было (байт):  192


1) Измените тип данных колонки type на category. Как изменился размер датафрейма?

In [12]:
print('Был тип:', my_data.type.dtype)
my_data.type = my_data.type.astype('category')
print('Стал тип: ', my_data.type.dtype)
new_mem1 = sum(my_data.memory_usage().values)
print('Всего байт стало (байт): ', new_mem1)
print('Датафрейм изменился на (байт): ', old_mem - new_mem1)

Был тип: object
Стал тип:  category
Всего байт стало (байт):  288
Датафрейм изменился на (байт):  -96


2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

In [14]:
print('Был тип:', my_data.value.dtype)
my_data.value = my_data.value.astype('int8')
print('Стал тип: ', my_data.value.dtype)
new_mem2 = sum(my_data.memory_usage().values)
print('Всего байт стало (байт): ', new_mem2)
print('Датафрейм изменился на (байт): ', new_mem1 - new_mem2)
print('Датафрейм в целом изменился на (байт): ', old_mem - new_mem2)

Был тип: int8
Стал тип:  int8
Всего байт стало (байт):  260
Датафрейм изменился на (байт):  28
Датафрейм в целом изменился на (байт):  -68


# Задание 7
Любым удобным для вас способом создайте ``dataframe`` c именем ``my_data``, в котором две колонки c именами (``type`` - строки, ``value`` - числа с плавающей точкой) и десять тысяч (10 000) наблюдений в каждой колонке. В колонке ``type`` должно быть 10 уникальных значений.

```python
my_data.shape
____________
(10000, 2)
```

Какой размер созданного вами датафрейма? (Подумайте, что лучше использовать - информацию из метода df.info() или информацию из метода df.memory_usage()?)

In [15]:
N = 10000
types = np.random.randint(0, 10, size=N)
values = np.random.uniform(-30, 50, size=N)
my_data2 = pd.DataFrame({'type': types, 'value': values})
print(my_data2.shape)
print(my_data2.memory_usage())
old_mem2 = sum(my_data2.memory_usage().values)
print('Всего байт было (байт): ', old_mem2)

(10000, 2)
Index      128
type     80000
value    80000
dtype: int64
Всего байт было (байт):  160128


1) Измените тип данных колонки type на category. Как изменился размер датафрейма?

In [16]:
print('Был тип:', my_data2.type.dtype)
my_data2.type = my_data2.type.astype('category')
print('Стал тип: ', my_data2.type.dtype)
new_mem3 = sum(my_data2.memory_usage().values)
print('Всего байт стало (байт): ', new_mem3)
print('Датафрейм изменился на (байт): ', old_mem2 - new_mem3)

Был тип: int64
Стал тип:  category
Всего байт стало (байт):  90508
Датафрейм изменился на (байт):  69620


2) Измените тип данных колонки value на менее жадный. Как изменился размер датафрейма?

In [17]:
print('Был тип:', my_data2.value.dtype)
print('Был диапазон значений: от', my_data2.value.min(), 'до', my_data2.value.max())
my_data2.value = my_data2.value.astype('float32')
print('Стал тип: ', my_data2.value.dtype)
print('Стал диапазон значений: от', my_data2.value.min(), 'до', my_data2.value.max())
new_mem4 = sum(my_data2.memory_usage().values)
print('Всего байт стало (байт): ', new_mem4)
print('Датафрейм изменился на (байт): ', new_mem3 - new_mem4)

Был тип: float64
Был диапазон значений: от -29.983572881509872 до 49.9947866974823
Стал тип:  float32
Стал диапазон значений: от -29.983572 до 49.994785
Всего байт стало (байт):  50508
Датафрейм изменился на (байт):  40000


Во сколько раз уменьшился размер исходного датафрейма после выполнения этих двух операций?

In [18]:
print('Датафрейм в целом изменился на (байт): ', old_mem2 - new_mem4)

Датафрейм в целом изменился на (байт):  109620


#### Для решения дальнейших задач мы будем использовать следующий датасет, загрузите его с помощью команды:

In [19]:
df = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat.csv')

In [109]:
df

V1    V2 V3   V4
0     2  13.0  B  1.0
1    -1   7.0  B  1.0
2     0  11.0  A  0.0
3     2  11.0  A  2.0
4     0  10.0  B -1.0
..   ..   ... ..  ...
495   1   8.0  A -1.0
496   3   8.0  A  1.0
497  -1  11.0  B  2.0
498   1  11.0  A  2.0
499   0   8.0  B  1.0

[500 rows x 4 columns]

Примечание: все операции с исходным датафреймом должны быть ``inplace``. То есть исходный датафрейм в переменной ``df`` **должен** измениться

# Задание 8

В переменную с именем subset_1 сохраните только первые 19 строк и только 1 и 3 колонку.

In [20]:
subset_1 = df.iloc[:19, [0, 2]]
display(subset_1)

V1 V3
0    2  B
1   -1  B
2    0  A
3    2  A
4    0  B
5    2  A
6    0  A
7    1  A
8    0  B
9   -1  A
10   1  A
11  -2  A
12   0  B
13   1  A
14  -1  A
15   2  B
16   0  B
17   0  A
18   0  A

В переменную с именем subset_2 сохраните все строки кроме 2, 3 и 18 и только 2 и 4 колонку.

In [22]:
subset_2 = df.iloc[~df.index.isin([1, 2, 17]), [1, 3]]
display(subset_2)

V2   V4
0    13.0  1.0
3    11.0  2.0
4    10.0 -1.0
5    11.0  0.0
6     9.0  2.0
..    ...  ...
495   8.0 -1.0
496   8.0  1.0
497  11.0  2.0
498  11.0  2.0
499   8.0  1.0

[497 rows x 2 columns]

# Задание 9

В переменную subset_3 сохраните только те наблюдения, у которых значения переменной V1 строго больше 0, и значение переменной V3  равняется 'A'.

In [23]:
subset_3 = df[(df.V1 > 0) & (df.V3 == 'A')]
# Проверка, subset_5 должен быть пустой
subset_5 = subset_3[(subset_3.V1 <= 0) | (subset_3.V3 != 'A')]
display(subset_3.head())
display(subset_5)

V1    V2 V3   V4
3    2  11.0  A  2.0
5    2  11.0  A  0.0
7    1   9.0  A  1.0
10   1  10.0  A  1.0
13   1  12.0  A  3.0

Empty DataFrame
Columns: [V1, V2, V3, V4]
Index: []

В переменную  subset_4  сохраните только те наблюдения, у которых значения переменной V2  не равняются 10, или значения переменной V4 больше или равно 1.

In [24]:
subset_4 = df[(df.V2 != 10.0) | (df.V4 >= 1.0)]
# Проверка, subset_6 должен быть пустой
subset_6 = subset_4[(subset_4.V2 == 10) & (subset_4.V4 < 1.0)]
display(subset_4.head())
display(subset_6)

V1    V2 V3   V4
0   2  13.0  B  1.0
1  -1   7.0  B  1.0
2   0  11.0  A  0.0
3   2  11.0  A  2.0
5   2  11.0  A  0.0

Empty DataFrame
Columns: [V1, V2, V3, V4]
Index: []

# Задание 10
Добавьте следующие колонки в df:

1) V5 = V1 + V4
2) V6 = **натуральный** логарифм переменной V2

In [25]:
df['V5'] = df['V1'] + df['V4']
df['V6'] = np.log(df['V2'])
display(df.head())

V1    V2 V3   V4   V5      V6
0   2  13.0  B  1.0  3.0  2.5649
1  -1   7.0  B  1.0  0.0  1.9459
2   0  11.0  A  0.0  0.0  2.3979
3   2  11.0  A  2.0  4.0  2.3979
4   0  10.0  B -1.0 -1.0  2.3026

# Задание 11

Переименуйте колонки в df.

1) V1 -> session_value

2) V2 -> group

3) V3 -> time

4) V4 -> n_users

In [26]:
df.rename(columns={
    'V1': 'session_value',
    'V2': 'group',
    'V3': 'time',
    'V4': 'n_users'
}, inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   session_value  500 non-null    int64  
 1   group          500 non-null    float64
 2   time           500 non-null    object 
 3   n_users        500 non-null    float64
 4   V5             500 non-null    float64
 5   V6             500 non-null    float64
dtypes: float64(4), int64(1), object(1)
memory usage: 23.6+ KB


# Задание 12

In [27]:
my_stat = pd.read_csv('https://stepik.org/media/attachments/course/4852/my_stat_1.csv')

In [93]:
my_stat


session_value  time group  n_users
0            0.0    12     B        9
1            NaN    11     A       -1
2            1.0     8     A        1
3            2.0     9     B        3
4            2.0    10     B        9
5            3.0     8     A        8
6            NaN    11     B        5
7            0.0     9     A        4
8            0.0     8     B      -11
9            0.0     9     A      -20

В датафрейме ``my_stat`` в колонке ``session_value`` замените все пропущенные значения на нули.


In [28]:
my_stat.session_value.fillna(0, inplace=True)
my_stat

session_value  time group  n_users
0            0.0    12     B        9
1            0.0    11     A       -1
2            1.0     8     A        1
3            2.0     9     B        3
4            2.0    10     B        9
5            3.0     8     A        8
6            0.0    11     B        5
7            0.0     9     A        4
8            0.0     8     B      -11
9            0.0     9     A      -20

В колонке ``n_users`` замените все отрицательные значения на медианное значение переменной ``n_users`` (без учета отрицательных значений, разумеется).

In [29]:
med = int(my_stat[my_stat.n_users >= 0]['n_users'].median())
my_stat.loc[my_stat.n_users < 0, 'n_users'] = med
my_stat


session_value  time group  n_users
0            0.0    12     B        9
1            0.0    11     A        5
2            1.0     8     A        1
3            2.0     9     B        3
4            2.0    10     B        9
5            3.0     8     A        8
6            0.0    11     B        5
7            0.0     9     A        4
8            0.0     8     B        5
9            0.0     9     A        5